server:
  port: 8080

spring:
  application:
    name: keda-k8s-product-app
  datasource:
    url: jdbc:mysql://localhost:3307/product_catalog?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: appuser
    password: apppassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: keda-k8s-product-app

logging:
  level:
    '[com.productcatalog]': INFO
    '[org.springframework.web]': INFO
    '[org.hibernate.SQL]': WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
