server:
  port: 8080

spring:
  application:
    name: keda-k8s-product-app
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DATABASE:product_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:appuser}
    password: ${MYSQL_PASSWORD:apppassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      access: UNRESTRICTED
    prometheus:
      access: UNRESTRICTED
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        '[http.server.requests]': true
      slo:
        '[http.server.requests]': 50ms,100ms,200ms,500ms,1s,2s

logging:
  level:
    '[com.productcatalog]': INFO
    '[org.springframework.web]': INFO
    '[org.hibernate.SQL]': WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
