apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s     # Check for metrics every 5 seconds
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'spring-boot-product-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['product-service:8080'] # Your Spring Boot Service name and container port
